version: "3"

services:
  # main components
  ccgateway:
    build:
      context: .
      dockerfile: ./cmd/gateway/Dockerfile
    restart: always
    links:
      - db
      - redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      loki:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - ./config:/etc/concurrent/:ro
    networks:
      - external
      - internal
    logging:
      driver: loki
      options: 
        loki-url: http://localhost:3100/loki/api/v1/push

  ccapi:
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
    restart: always
    links:
      - db
      - redis
      - loki
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      loki:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - ./config:/etc/concurrent/:ro
    networks:
      - external
      - internal
    logging:
      driver: loki
      options: 
        loki-url: http://localhost:3100/loki/api/v1/push

  ccwebui:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    restart: always
    links:
      - loki
    depends_on:
      loki:
        condition: service_started
    ports:
      - "8001:80"
    networks:
      - internal
    logging:
      driver: loki
      options: 
        loki-url: http://localhost:3100/loki/api/v1/push

  db:
    restart: always
    image: postgres
    links:
      - loki
    depends_on:
      loki:
        condition: service_started
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 5s
      retries: 20
    volumes:
      - ./_composeData/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=concurrent"
    networks:
      - internal
    logging:
      driver: loki
      options: 
        loki-url: http://localhost:3100/loki/api/v1/push

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      - "DATA_SOURCE_NAME=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable"
    ports:
      - 9187:9187
    networks:
      - internal

  redis:
    restart: always
    image: redis
    links:
      - loki
    depends_on:
      loki:
        condition: service_started
    volumes:
      - ./_composeData/redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20
    ports:
      - "6379:6379"
    networks:
      - internal
    logging:
      driver: loki
      options: 
        loki-url: http://localhost:3100/loki/api/v1/push

  redis-exporter:
    image: oliver006/redis_exporter:v1.6.0-alpine
    ports:
      - 9121:9121
    networks:
      - internal
    command:
      - '--redis.addr=redis://redis:6379'

  memcached:
    image: memcached
    links:
      - loki
    depends_on:
      loki:
        condition: service_started
    ports:
      - "11211:11211"
    networks:
      - internal
    logging:
      driver: loki
      options: 
        loki-url: http://localhost:3100/loki/api/v1/push

  memcached-exporter:
    image: prom/memcached-exporter:v0.6.0
    ports:
      - 9150:9150
    networks:
      - internal
    command:
      - '--memcached.address=memcached:11211'

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./dev/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./dev/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dev/dashboards:/etc/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    networks:
      - external
      - internal

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./dev/prometheus.yaml:/etc/prometheus.yaml
      - ./_composeData/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - internal

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./_composeData/loki:/data/loki
    networks:
      - internal

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./dev/tempo.yaml:/etc/tempo.yaml
      - ./_composeData/tempo:/tmp/tempo
    networks:
      - internal

networks:
  external:
  internal:
    internal: true
 
