services:
  gateway:
    image: ghcr.io/totegamma/ccgateway:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./etc:/etc/concrnt/:ro
    networks:
      - external
      - internal

  api:
    image: ghcr.io/totegamma/ccapi:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./etc:/etc/concrnt/:ro
    expose:
      - 8000
    networks:
      - external
      - internal

  webui:
    image: ghcr.io/totegamma/ccwebui:latest
    restart: always
    expose:
      - 80
    networks:
      - external
      - internal

  hyperproxy:
    image: ghcr.io/concrnt/hyperproxy:latest
    restart: always
    expose:
      - 8080
    networks:
      - external
      - internal

# apbridge:
#   image: ghcr.io/concrnt/ccworld-ap-bridge:latest
#   restart: always
#   depends_on:
#     db:
#       condition: service_healthy
#     redis:
#       condition: service_healthy
#   volumes:
#     - ./etc:/etc/concrnt/:ro
#   expose:
#     - 8000
#   networks:
#     - external
#     - internal

# mediaserver:
#   image: ghcr.io/totegamma/cc-media-server:latest
#   restart: always
#   links:
#     - db
#   depends_on:
#     db:
#       condition: service_healthy
#   expose:
#     - 8000
#   environment:
#     bucketName:
#     endpointUrl:
#     accessKeyId:
#     accessKeySecret:
#     publicBaseUrl:
#     quota:
#     forcePathStyle:
#     db_dsn: "host=db user=postgres password=postgres dbname=concurrent"
#   networks:
#     - internal

  db:
    restart: always
    image: postgres:16-bookworm
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 5s
      retries: 20
    volumes:
      - ./_composeData/db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=concurrent"
    expose:
      - 5432
    networks:
      - internal

  redis:
    restart: always
    image: redis:7-bookworm
    volumes:
      - ./_composeData/redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20
    expose:
      - 6379
    networks:
      - internal

  memcached:
    restart: always
    image: memcached:1.6-bookworm
    expose:
      - 11211
    networks:
      - internal
  
networks:
  external:
  internal:
    internal: true
