version: "3"

services:
  gateway:
    image: ghcr.io/totegamma/ccgateway:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./config:/etc/concurrent/:ro
    networks:
      - external
      - internal

  api:
    image: ghcr.io/totegamma/ccapi:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./config:/etc/concurrent/:ro
    expose:
      - 8000
    networks:
      - external
      - internal

  webui:
    image: ghcr.io/totegamma/ccwebui:latest
    restart: always
    expose:
      - 80
    networks:
      - external
      - internal

  summary:
    image: ghcr.io/rassi0429/url-summary:latest
    restart: always
    environment:
      - PORT=8080
    expose:
      - 8080
    networks:
      - external

  apbridge:
    image: ghcr.io/totegamma/ccworld-ap-bridge:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./config:/etc/concurrent/:ro
    expose:
      - 8000
    networks:
      - internal

  db:
    restart: always
    image: postgres
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 5s
      retries: 20
    volumes:
      - ./_composeData/db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=concurrent"
    expose:
      - 5432
    networks:
      - internal

  redis:
    restart: always
    image: redis
    volumes:
      - ./_composeData/redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20
    expose:
      - 6379
    networks:
      - internal
  
networks:
  external:
  internal:
    internal: true
