
apConfig:
  fqdn: example.com
  # 通常通り、concrnt.worldでアカウントを作成し、そのアカウントの秘密鍵を入力します。
  # **APIサーバーの秘密鍵を使いまわさないように！！！**
  # 途中で変更すると、タイムラインの権限周りを全て修正する必要があるので注意！
  proxyPriv: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# config.yamlとほぼ同じ内容
server:
  apiAddr: "gateway"
  dsn: "host=db user=postgres password=postgres dbname=concurrent port=5432 sslmode=disable"
  redisAddr: "redis:6379"
  redisDB: 0
  memcachedAddr: "memcached:11211"
  traceEndpoint: "tempo:4318"
  enableTrace: false
  repositoryPath: "/var/lib/concurrent"
  captchaSitekey: "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
  captchaSecret: "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"

nodeInfo:
  openRegistration: false
  metadata:
    nodeName: 'example.com'
    nodeDescription: 'description'
    maintainer:
      name: 'your_name'
      email: 'your_email@example.com'
    themeColor: '#0476d9'
