# this is example. you must replace ccid and keys before deploy.
server:
  dsn: "host=db user=postgres password=postgres dbname=concurrent port=5432 sslmode=disable"
  redisAddr: "redis:6379"
  redisDB: 0
  memcachedAddr: "memcached:11211"
  traceEndpoint: "tempo:4318"
  enableTrace: false
  repositoryPath: "/var/lib/concurrent"
  captchaSitekey: "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
  captchaSecret: "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"
  # push notification key. you can generate with conctl command. `conctl gen vapid`
  vapidPublicKey: ""
  vapidPrivateKey: ""

concrnt:
  # fqdn is instance ID
  # It is really hard and not recommended to change this value after node started
  fqdn: example.tld
  # 'open' or 'invite' or 'close'
  # you can generate invite code with conctl command. `conctl gen invite`
  registration: open
  # network
  # for testing: concrnt-devnet, for production: concrnt-mainnet
  dimension: concrnt-mainnet
  # server agent account
  # you can generate with conctl command. `conctl gen identity`
  privatekey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

profile:
  nickname: concurrent-domain
  description: domain description
  logo: 'https://concurrent.world/concurrent.png'
  wordmark: ''
  themeColor: '#0476d9'
  maintainerName: notset
  maintainerEmail: notset@example.com

