name: Release_Web

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build
        run: pnpm i && pnpm build

      - name: zip the build
        run: zip -r web.zip ./dist

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./web.zip
          asset_name: web.zip
          asset_content_type: application/zip


